name: build

on:
  #push:
    #branches: [ "dev" ]
  #pull_request:
    #branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BuildDir: "[CP] SilenceIsGolden"
      Manifest: "manifest.json"
      Content: "content.json"
      Documentation: "LICENSE README.md release-notes.md"
      Assets: "assets"
      I18n: "i18n"

    steps:
      - uses: actions/checkout@v4

      - name: Format JSON
        run: find "${{ github.workspace }}" -name '*.json' -print0 | xargs -0 -L1 -- sed -i -e '/^[[:space:]]*\/\//d' -e '/^[[:space:]]*$/d'

      - name: Validate JSON
        run: find "${{ github.workspace }}" -name '*.json' -print0 | xargs -0 -L1 -- python -mjson.tool
      
      - name: Create build directory
        run: mkdir "$BuildDir"

      - name: Update version and copy manifest
        run: sed -e 's/^\([[:space:]]*"Version":\([[:space:]]\)*"\)[0-9]\+\.[0-9]\+\.[0-9]\+\(",[[:space:]]*\)$/\1\20.0.0\2/' "${{ github.workspace }}/$Manifest" > "$BuildDir/$Manifest"

      - name: Copy content
        run: cp "${{ github.workspace }}/$Content" "$BuildDir/"

      - name: Copy documentation
        run: for i in $Documentation; do cp "${{ github.workspace }}/$i" "$BuildDir/"; done

      - name: Copy assets
        run: cp -R "${{ github.workspace }}/$Assets" "$BuildDir/"

      - name: Copy i18n
        run: cp -R "${{ github.workspace }}/$I18n" "$BuildDir/"

      - name: Show info
        run: |
          ls -R "$BuildDir/"
          cat "$BuildDir/$Manifest"
