name: validate

on:
  push:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      Manifest: "manifest.json"
      ReleaseNotes: "release-notes.md"

    steps:
      - uses: actions/checkout@v4

      - name: Format JSON
        run: find "${{ github.workspace }}" -name '*.json' -print0 | xargs -0 -L1 -- sed -i -e '/^[[:space:]]*\/\//d' -e '/^[[:space:]]*$/d'

      - name: Validate JSON
        run: find "${{ github.workspace }}" -name '*.json' -print0 | xargs -0 -L1 -- python -mjson.tool
      
      - name: Verify version
        run: |
          Version=$(jq -r .Version "${{ github.workspace }}/$Manifest")
          echo Checking release notes for version $Version...
          grep '^[[:space:]]*##[[:space:]]*'"$Version" "$ReleaseNotes"
